# Generated by Django 5.2.1 on 2025-05-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_workassignments_isdone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='addharNo',
        ),
    ]
